version: '3.9'

services:
  app:
    container_name: user-management
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - .:/app
    restart: always

  db:
    container_name: postgres-users
    env_file: database.conf
    image: postgres:12-alpine
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes: 
      - ./postgres:/var/lib/pgsql/12/data
    
